services:
  socket-proxy:
    image: 'tecnativa/docker-socket-proxy:0.3.0'
    container_name: 'socket-proxy'
    environment:
      - 'CONTAINERS=1'
    expose:
      - '2375'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: 'always'
    networks:
      - 'internal'

  traefik:
    image: 'traefik:v3.1'
    container_name: 'traefik'
    command:
      # Docker
      - '--providers.docker'
      - '--providers.docker.endpoint=tcp://socket-proxy:2375'
      - '--providers.docker.exposedbydefault=false'
      # Dashbaord
      - '--api.dashboard=true'
      - '--api.insecure=false'
      # Entrypoints
      - '--entryPoints.websecure.address=:443'
      - '--entrypoints.websecure.asDefault=true'
      - '--entrypoints.websecure.http.tls.certresolver=default'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      # ACME
      - '--certificatesresolvers.default.acme.tlschallenge=true'
      - '--certificatesresolvers.default.acme.email=${TRAEFIK_ACME_EMAIL}'
      - '--certificatesresolvers.default.acme.storage=/LetsEncrypt/acme.json'
    labels:
      - 'traefik.enable=true'
      # Router
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.mikkel.dev`)'
      - 'traefik.http.routers.dashboard.service=api@internal'
      # Basic Auth (Middleware)
      - 'traefik.http.routers.dashboard.middlewares=auth'
      - 'traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USER}:{SHA}${TRAEFIK_BASIC_AUTH_PASSWORD}'
    depends_on:
      - 'socket-proxy'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'LetsEncrypt:/LetsEncrypt'
    restart: 'always'
    networks:
      - 'internal'
      - 'web'

  app:
    image: 'ghcr.io/mikkelpetersen/mikkel-dev:main'
    labels:
      - 'traefik.enable=true'
      # Router
      - 'traefik.http.routers.app.rule=Host(`mikkel.dev`) || Host(`www.mikkel.dev`)'
      - 'traefik.http.routers.app.entrypoints=websecure'
      - 'traefik.http.routers.app.tls.certresolver=default'
      # Redirect to Apex
      - 'traefik.http.middlewares.redirect-to-apex.redirectregex.regex=^https://www\.(.*)'
      - 'traefik.http.middlewares.redirect-to-apex.redirectregex.replacement=https://$${1}'
      - 'traefik.http.middlewares.redirect-to-apex.redirectregex.permanent=true'
      - 'traefik.http.routers.app.middlewares=redirect-to-apex'
    deploy:
      mode: 'replicated'
      replicas: 3
    depends_on:
      - 'traefik'
    restart: 'always'
    networks:
      - 'internal'
      - 'web'

networks:
  internal:
    name: 'internal'
    internal: true
  web:
    name: 'web'
    internal: false

volumes:
  LetsEncrypt:
    name: 'LetsEncrypt'
